### PR TITLE
added support for tls over ssl

### PR DESCRIPTION
**Pull request by l0st3d**

### CODE REVIEW

**Comment by bskinny** [comment]
Hello @l0st3d . I am not sure issuing StartTLS over an existing TLS connection is a warranted action. Would you mind explaining the reasoning behind this?

**Comment by pauldorman** [comment]
I concur with @bskinny, I think connection options should be "Plain", "SSL (LDAPS)", and "StartTLS", with default ports being 389,636, and 389 respectively. Otherwise, great (and overdue) addition!

**Comment by l0st3d** [comment]
Hey. I agree with your assessment. However, this change was required by a strange setup internally, so I thought I'd contribute it back. As it happens we've solved our infrastructure problem and don't need this "feature" now. Seeing as the list of people asking for this is back down to zero I suggest you ignore me and go about your day ;) ... Many thanks for the work, it's much appreciated.

**Comment by bskinny** [comment]
Understood. Thanks for the explanation @l0st3d

**Pull request closed without merging**
