### PR TITLE
added example of working with a connection pool

### PR DESCRIPTION
**Pull request by yogthos**
I just spent a bit of time figuring out why `bind?` didn't authenticate the connection. Looking through the source I noticed that `connect` returns an unauthenticated pool instance.

### CODE REVIEW

**Comment by bskinny** [comment]
Hi @yogthos . Actually the bind? function should be passed a pool if you want to authenticate but have the connection retain it's original authorization DN. If you need the connection's authorization DN to stay as the bind DN, then you should check out a connection from the pool and work with that. E.g. use (.getConnection pool).

**Comment by bskinny** [comment]
I will annotate the connect and bind? examples as they are confusing. The connect examples should all contain credentials. And a bind? example is needed for the instance of LDAPConnection: It's necessary to show the getConnection and releaseConnection methods needed for this interaction.

**Comment by yogthos** [comment]
Sounds good, it was a bit confusing why it wasn't working, so had to dig through the source a bit to figure out what to do. Great library though, saved me a lot of time! :)

**Comment by bskinny** [comment]
It is certainly confusing, but still better than using the LDAP SDK directly. I'll close this pull request since there is now an example in the README for the bind? function which demonstrates the get-connection, release-connection.

Here it is to save you the effort.
`(let [conn (ldap/get-connection pool)
          user-dn "uid=user.1,ou=people,dc=example,dc=com"
          user-password "password"]
      (try
        (ldap/bind? conn user-dn user-password)
        (ldap/modify conn user-dn {:replace {:description "On sabatical"}})
        (finally (ldap/release-connection pool conn))))`

**Comment by yogthos** [comment]
Looks great, thanks

**Pull request closed without merging**
