### PR TITLE
Fix broken StartTLS when using :bind-dn in (ldap/connect)

### PR DESCRIPTION
**Pull request by philippnormann**

### CODE REVIEW

**Comment by alphaone** [comment]
This corresponds with the example here: https://docs.ldap.com/ldap-sdk/docs/javadoc/com/unboundid/ldap/sdk/StartTLSPostConnectProcessor.html

```Java
 // Use the StartTLS extended operation to secure the connection.
 ExtendedResult startTLSResult = connection.processExtendedOperation(
      new StartTLSExtendedRequest(sslContext));
```

**Comment by bskinny** [comment]
Thanks @philippnormann and @alphaone. I will get this fix in later today (East Coast US time).

**Comment by philippnormann** [comment]
Thanks for merging @bskinny! Have you already pushed a new release?

**Comment by bskinny** [comment]
@philippnormann Not yet. I need to look at another PR opened a few days ago - will look at that today - and then send the release request to Paul, the project owner.

**Pull request merged**
